### ISSUE TITLE
Two Loader Active while selecting Login with Email or Login with Phone Number

### ISSUE THREAD

**Issue by gajjardarshithasmukhbhai** [sesto-dev/next-prisma-tailwind-ecommerce#5]
**Describe the bug**
- Hi Team, I gone through this website: https://pasargad.vercel.app/. but while try to login with gmail and phone number. both preloaders are active instead of one. 

**Expected behavior**
- One Preloader Active: either We selected login with Gmail and login with phone number. 

**Screenshots**
![image](https://github.com/user-attachments/assets/2edfb769-03dc-4dac-93cb-dd46a1c3b8c8)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser: chrome
 - Version: lst
 
**Additional context**
- FYI - Not Able to log in with anyone(email or phone number)

**Comment by sesto-dev** [comment]
Thank you for reporting this issue. Two loaders being active was the default behavior because we have a single state for the login function being in state of fetching data but there was indeed a problem with not being able to login due to OTP emails not being sent. The problem was that the newer versions of ``react-email/render`` required awaiting the results of their ``render()`` function which I solved in the last commit [cffb844](https://github.com/sesto-dev/next-prisma-tailwind-ecommerce/commit/cffb844fd9ff031aaf66a3a86fafc24b6794a143)
